# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 3.2.0"

gem "rails", "~> 8.0.0"
# Stdlib extraction (Ruby 3.4+): CSV is not guaranteed on the load path without this gem.
gem "csv"
gem "bcrypt", "~> 3.1"
gem "propshaft"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 6.0"
gem "tailwindcss-rails", "~> 3.0"
gem "plaid"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri mingw mswin x64_mingw ], require: "debug/prelude"
end

group :development do
  gem "foreman"
  gem "web-console"
end
